# Generated by Django 5.2.5 on 2026-07-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('geography', 'Geography'), ('personnel', 'Personnel'), ('weapons', 'Weapons')], max_length=20, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge dataset',
                'verbose_name_plural': 'Knowledge datasets',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('citome', 'Citome'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='ollama', help_text='Which LLM backend to use.', max_length=20)),
                ('base_url', models.CharField(default='http://localhost:11434', help_text='Base URL of the LLM backend.', max_length=255)),
                ('base_model', models.CharField(default='aya-expanse:8b', help_text='Base model used when (re)building the custom wargaming model.', max_length=120)),
                ('wargaming_model', models.CharField(default='wargaming:unified', help_text='Model name served at inference time.', max_length=120)),
                ('api_key', models.CharField(blank=True, default='', help_text='API key for hosted providers (leave blank for local Ollama).', max_length=255)),
                ('temperature', models.FloatField(default=0.4)),
                ('top_p', models.FloatField(default=0.9)),
                ('num_predict', models.IntegerField(default=1400, help_text='Max tokens to generate.')),
                ('num_ctx', models.IntegerField(default=6144, help_text='Context window size.')),
                ('repeat_penalty', models.FloatField(default=1.1)),
                ('conversation_history_limit', models.IntegerField(default=4, help_text='How many previous messages to include as context.')),
                ('request_timeout_seconds', models.IntegerField(default=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Config',
                'verbose_name_plural': 'LLM Config',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('unified_system', 'Runtime system prompt'), ('training_system', 'Training system prompt')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(help_text='The full prompt text.')),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, the built-in default prompt is used instead.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
