# Generated by Django 5.2.5 on 2026-07-27 07:53

import django.db.models.deletion
import orchestrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_sync_knowledge_datasets'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Allowed: .txt, .pdf, .docx (max 10 MB). Used automatically in chat answers.', upload_to=orchestrator.models.knowledge_document_upload_to)),
                ('file_type', models.CharField(blank=True, choices=[('txt', 'Text'), ('pdf', 'PDF'), ('docx', 'Word')], default='', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive documents are kept but not used for answering questions.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge document',
                'verbose_name_plural': 'Knowledge documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_hints', models.TextField(blank=True, default='', help_text='Lowercased searchable form of the chunk.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='orchestrator.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Knowledge document chunk',
                'verbose_name_plural': 'Knowledge document chunks',
                'ordering': ['document_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_knowledge_document_chunk_index')],
            },
        ),
    ]
