"""
Django settings for war_game project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from war_game.project_config import (
    DATABASE_PATH,
    DJANGO_ALLOWED_HOSTS,
    DJANGO_DEBUG,
    DJANGO_DEFAULT_AUTO_FIELD,
    DJANGO_INSTALLED_APPS,
    DJANGO_LANGUAGE_CODE,
    DJANGO_MIDDLEWARE,
    DJANGO_SECRET_KEY,
    DJANGO_STATIC_URL,
    DJANGO_TEMPLATE_DIRS,
    DJANGO_TIME_ZONE,
    LLM_PROVIDER_CONFIG,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DJANGO_DEBUG

ALLOWED_HOSTS = DJANGO_ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = DJANGO_INSTALLED_APPS

MIDDLEWARE = DJANGO_MIDDLEWARE

ROOT_URLCONF = 'war_game.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': DJANGO_TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'war_game.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATABASE_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = DJANGO_LANGUAGE_CODE

TIME_ZONE = DJANGO_TIME_ZONE

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = DJANGO_STATIC_URL
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = DJANGO_DEFAULT_AUTO_FIELD

# LLM Configuration
LLM_CONFIG = LLM_PROVIDER_CONFIG


# ---------------------------------------------------------------------------
# Unfold admin theme
# ---------------------------------------------------------------------------
UNFOLD = {
    "SITE_TITLE": _("Wargaming Admin"),
    "SITE_HEADER": _("Wargaming Control Center"),
    "SITE_SUBHEADER": _("Config · Prompts · Knowledge · Conversations"),
    "SITE_SYMBOL": "military_tech",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_LANGUAGES": False,
    "BORDER_RADIUS": "8px",
    "COLORS": {
        "primary": {
            "50": "236 253 245",
            "100": "209 250 229",
            "200": "167 243 208",
            "300": "110 231 183",
            "400": "52 211 153",
            "500": "16 185 129",
            "600": "5 150 105",
            "700": "4 120 87",
            "800": "6 95 70",
            "900": "6 78 59",
            "950": "2 44 34",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Overview"),
                "separator": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("LLM Service"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Model & Config"),
                        "icon": "tune",
                        "link": reverse_lazy("admin:orchestrator_llmconfig_changelist"),
                    },
                    {
                        "title": _("Prompts"),
                        "icon": "chat_paste_go",
                        "link": reverse_lazy("admin:orchestrator_prompt_changelist"),
                    },
                ],
            },
            {
                "title": _("Knowledge Base"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Data (Geo / Personnel / Weapons)"),
                        "icon": "database",
                        "link": reverse_lazy("admin:orchestrator_knowledgebase_changelist"),
                    },
                ],
            },
            {
                "title": _("Chat"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Conversations"),
                        "icon": "forum",
                        "link": reverse_lazy("admin:orchestrator_conversation_changelist"),
                    },
                    {
                        "title": _("Messages"),
                        "icon": "mail",
                        "link": reverse_lazy("admin:orchestrator_message_changelist"),
                    },
                ],
            },
            {
                "title": _("Administration"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
